name: Code Quality Checks

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

# Optimized for speed and essential quality checks only
jobs:
  quality-checks:
    name: Lint & Type Check
    runs-on: ubuntu-latest
    
    # Single Node.js version for faster execution
    # Using Node 20 LTS for latest features and stability
    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        # Fetch only the latest commit for speed
        fetch-depth: 1
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        # Cache npm dependencies for faster subsequent runs
        cache: 'npm'
        # Optionally cache node_modules directly
        cache-dependency-path: package-lock.json
    
    - name: Install dependencies
      run: npm ci --prefer-offline --no-audit
      # --prefer-offline: Use cache when possible
      # --no-audit: Skip security audit for speed (run separately if needed)
    
    # Run checks in parallel where possible
    - name: Run ESLint
      run: npm run lint
      # Catches code style issues, potential bugs, and enforces best practices
    
    - name: Run TypeScript type checking
      run: npm run type-check
      # Ensures type safety across the entire codebase
      # Critical for catching runtime errors at build time
    
    # Optional: Add Prettier check if not handled by ESLint
    - name: Check code formatting
      run: npm run format:check
      continue-on-error: false
